### ISSUE TITLE
Firewall not appropriately open when using generated public port

### ISSUE THREAD

**Issue by miguelaferreira** [MissionCriticalCloud/vagrant-cloudstack#112]
I've removed the public port on a working config and a public port gets generated (as expected) but the firewall rule does get the generated public port.

My config:

``` ruby
cloudstack.pf_open_firewall = false
cloudstack.firewall_rules = [{"ipaddress" => "A.B.C.D", "cidrlist" =>  "E.F.G.H/32", "protocol" =>  "tcp"}]
```

The resulting firewall rule in Cloudstack misses the start- and end-port.

Looking into the code I find that the generated public port is not propagated to the specified firewall rules.
That means we must use the trusted networks attribute to have the firewall well configured.

I guess this is not a bug, but maybe the documentation needs to be updated to explain how to use this.

**Comment by bheuvel** [comment]
Perhaps we need to start using the Wiki?

**Comment by bheuvel** [comment]
@miguelaferreira indeed the `pf_trusted_networks` is used for that.
Perhaps documentation improved in the mean time?

**Comment by miguelaferreira** [comment]
So you mean this is the expected behavior?

**Comment by bheuvel** [comment]
Apparently not expected by everyone :wink:

When you use the `pf_trusted_networks`, that firewall rule will be generated anyway, so no reason to specify the rule.

For Windows two ports will be generated; WinRM, RDP.
When using `pf_trusted_networks`, a rule will be generated for both.

_Therefore_, also with the double port for Windows, did not default a "missing" port in a/all rules to the generated port(s).

**Comment by bheuvel** [comment]
@miguelaferreira hope this answered your question:

> When you use the `pf_trusted_networks`, that firewall rule will be generated anyway, so no reason to specify the rule.

If not, feel free to open this again 🙂

**Comment by miguelaferreira** [comment]
Yes @bheuvel, thanks! 

👍
