### ISSUE TITLE
Trusted network CIDR would best be an Array

### ISSUE THREAD

**Issue by miguelaferreira** [MissionCriticalCloud/vagrant-cloudstack#113]
This way we can better integrate with other tools (like kitchen e.g.).

**Comment by bheuvel** [comment]
When using the latest PR created  at kitchen-vagrant https://github.com/test-kitchen/kitchen-vagrant/pull/167 ;

``` YAML
   pf_trusted_networks:
      - "a.a.a.a"
      - "b.b.b.b"
```

resulting/requested Vagrantfile:

``` ruby
pf_trusted_network = ["a.a.a.a", "b.b.b.b"]
```
