### ISSUE TITLE
allow nfs mounting

### ISSUE THREAD

**Issue by thecodeassassin** [MissionCriticalCloud/vagrant-cloudstack#129]
hey All,

How much work would it be to support NFS mounts in the vagrant files? Currently you can only use rsync which makes the vagrant-cloudstack plugin less than ideal for code projects. I tried the rsync-auto flag but it doesn't seem to work.

**Comment by miguelaferreira** [comment]
Hi @thecodeassassin 

We tap into vagrant for the rsync support, and since vagrant supports NFS it should already work.
The only reason I can think of for it not working is the firewall on cloudstack.

Can you please explain what have you tried and what was the result?

**Comment by bheuvel** [comment]
@thecodeassassin Can you provide the further explanation? Or if it's already clear/solved, let us know so we can close this request.

**Comment by bheuvel** [comment]
@thecodeassassin closing this issue for now. If you still have a problem, we can re-open this issue any time.
