### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by vincentbernat** [MissionCriticalCloud/vagrant-cloudstack#145]
Hello!

I would be interested by a new release to get the fix in #134. The current master works for me but it is difficult for users to install the plugin from git.

Thanks!

**Comment by miguelaferreira** [comment]
Hi @vincentbernat 

Thanks for reaching out.
@bheuvel has been preparing a new release, but since there was not that much "pull", it started to loose priority and lag behind.
We will put some extra pressure to get that out, and we will ping you when it's done.

Cheers,

**Comment by miguelaferreira** [comment]
Hi @vincentbernat 

@bheuvel just pushed a new gem to rubygems.org
Please let us know if you have any issues.

Cheers

**Comment by bheuvel** [comment]
Release was made with PR #147
