### ISSUE TITLE
Add support for resolving projects by name.

### ISSUE THREAD

**Issue by lndbrg** [MissionCriticalCloud/vagrant-cloudstack#48]
Currently fog doesn't support the different project apis listed here:
https://cloudstack.apache.org/docs/api/apidocs-4.3/TOC_Root_Admin.html

I have registered an issue with fog:
https://github.com/fog/fog/issues/3015

**Comment by j00p34** [comment]
I think this has actually been fixed in fog on 5 december 2014.
