### ISSUE TITLE
Allow to override rsync arguments

### ISSUE THREAD

**Issue by vincentbernat** [MissionCriticalCloud/vagrant-cloudstack#61]
Hi!

It is currently not possible to override arguments provided to rsync. I would like to be able to use `--copy-links`. With regular rsync folders, this is something easy to do: http://docs.vagrantup.com/v2/synced-folders/rsync.html

Would it be possible to have something similar when using the Cloudstack provider?

**Comment by miguelaferreira** [comment]
Hi @vincentbernat 

@atsaki's commit a04addf887f606e20918a6ffdf7b9d4b65a300e5 changed the plugin to sue vagrant's builtin synched folders mechanism.
Does that address your issue?

**Comment by vincentbernat** [comment]
Yes, it works for me. Thanks! A release would be welcome.

**Comment by miguelaferreira** [comment]
Cool.

Just did that. check https://rubygems.org/gems/vagrant-cloudstack

**Comment by miguelaferreira** [comment]
Fixed in a04addf
