### ISSUE TITLE
Is the project actively maintained?

### ISSUE THREAD

**Issue by miguelaferreira** [MissionCriticalCloud/vagrant-cloudstack#62]
Hi all,

Together with a few colleagues, we've been testing this plugin and found some things we would like to contribute. Then we browsed the PRs and saw that some of those things were already implemented by @atsaki. We also saw that, although, people commented very positively in the PRs, they are still pending (the oldest one is from Nov last year).

So, our question is, are the original developers still maintaining the plugin?
Or, are there forks already being maintained independently?

Cheers,

**Comment by tobpal** [comment]
Hi,

Sorry to say but the original Developers have left Klarna, and we are not actively using it anymore therefor we do not maintain it.

We will update the description asap.

Kind regards

**Comment by miguelaferreira** [comment]
@tobpal Thanks for the quick reply.

Please let me use this post to ping the people that contributed the last so we can have a discussion about where to take the project.

ping @atsaki, @mindjiver, @lndbrg, @wico, @petrhosek  
Anyone willing to jointly take over the maintenance of the plugin?

**Comment by mindjiver** [comment]
Hi! Since me, @loa and @lndbrg are no longer employed by Klarna and have no access to a Cloudstack instance it's hard for us to perform any development or maintenance.

So if someone out there would like to take over the maintenance it would be great. I mostly did the release engineering parts of tagging and uploading the resulting gem.

**Comment by lndbrg** [comment]
I'd be happy to see the project live on, but not with me as one of the maintainers. :)

**Comment by loa** [comment]
Good old times :)

**Comment by miguelaferreira** [comment]
Hi guys,

Thanks for all the input.
We, at Schuberg Philis, would be happy to continue the project.
We run our cloud on Apache CloudStack and are actively contributing to that project as well.
So it would make much sense for us to pick this project up, since it is a key component for our development activities (i.e. it integrates two major tools we use).

Please let us know if you would be interested in passing on the development of vagrant-cloudstack to us. We would, of course, import the git tree with the original code and commits to our organisation in github, and take it from there.

**Comment by wico** [comment]
From my point of view: That's the best way forward!

**Comment by mindjiver** [comment]
@miguelaferreira I also developed/mainted the Packer builder for Cloudstack ( https://github.com/mindjiver/packer-cloudstack ) is that something you use as well?

**Comment by miguelaferreira** [comment]
@mindjiver Thanks. In principle yes. But I won't have the free cycles to commit to both projects. I've asked internally to see if someone steps up.

**Comment by miguelaferreira** [comment]
I've created a repo under our organisation https://github.com/schubergphilis/vagrant-cloudstack
I've moved the entire git tree there, and merged the pending PRs.

Once we are ready to make a new release, we will probably need some help with uploading it to RubyGems.org since you guys own the gem too.

@mindjiver I found colleagues interested in committing to the packer-cloudstack project.
Shall we do the same type of transfer for this project too? Or do you have something else in mind?

**Comment by mindjiver** [comment]
@miguelaferreira Either that or I would need a API end point to test towards. If your things are internal then I guess the best thing is to move over the development to your org. I'm happy to help out with any questions about the project.

**Comment by miguelaferreira** [comment]
@loa  could you add me to the gem project on rubygems.org?

My profile: https://rubygems.org/profiles/miguelaferreira

**Comment by miguelaferreira** [comment]
@mindjiver Well, I think that the best would be to transfer the project since our cloud is not public. However, if you still want to contribute we can try to find a solution to give you access to a testing environment.

**Comment by mindjiver** [comment]
@miguelaferreira It's fine by my if you continue development :smile: I have used CloudStack enough in my time.

**Comment by loa** [comment]
@miguelaferreira I'm not part of Klarna any longer. Me still being owner of the gem  is probably a mistake.

It's better if @wico changes the ownership since he's working at Klarna.

**Comment by atsaki** [comment]
@miguelaferreira I would be happy you continue development of this project :)

**Comment by wico** [comment]
@loa I'll look at it in a less busy minute.

**Comment by x20mar** [comment]
As a user, I too would be quite interested in seeing this plugin continue with development. I would help out in the coding but I don't know any Ruby

**Comment by wico** [comment]
@loa @mindjiver @lndbrg I will transfer that repo to @miguelaferreira 
+
I'll change the https://rubygems.org/gems/vagrant-cloudstack (gem)ownership to miguelferreira too.

Any dissenting votes?

**Comment by loa** [comment]
@wico Sounds great

**Comment by lndbrg** [comment]
:+1: 
:shipit:

**Comment by wico** [comment]
quorum reached. I'll start the repo-transfer now, the gem-ownerships comes tomorrow (I'm not at klarna actually).

**Comment by miguelaferreira** [comment]
Super! Thanks a lot guy.

**Comment by wico** [comment]
"You can only transfer a repository from an organization to yourself at this time" ;)

**Comment by miguelaferreira** [comment]
I guess that means you would need to do it in two steps?
I mean, I know it works from user to user, and from user to organisation.
I've never tried from organisation to user.

**Comment by wico** [comment]
"Something went wrong with that request. Please try again." ;)

However - check your inbox. There should be an incoming request.

**Comment by miguelaferreira** [comment]
I did get the request and accepted it :+1:

**Comment by wico** [comment]
perfect, done, looks good to me.

**Comment by miguelaferreira** [comment]
I will now start by updating the README, review PRs, etc

And along the way, move the repo to Shuberg Philis organisation

**Comment by wico** [comment]
Thanks. Please keep that little piece of code in a good shape. :) Especially @mindjiver will appreciate that!

**Comment by miguelaferreira** [comment]
We will do our best and contribution is, of course, always welcome.

**Comment by wico** [comment]
@loa FYI: the related gem is now owned by @miguelaferreira.

**Comment by wico** [comment]
@mindjiver OK with transfering packer-cloudstack to @miguelaferreira too? 

@miguelaferreira We probably continue using that packer-"plugin" in the future, but there should be no problem to contribute to you then.

**Comment by miguelaferreira** [comment]
@wico  I've asked @mindjiver to change the license of the packer project to Apache 2.0 because that fits best with our open-source software policy. However, if that is too much work we can also work with the Mozilla license, although not ideal.

What we can't do, is relicense it ourselves. So, the license we get from you is the one that stays. Hence the request.

I do have some colleagues very eager to start maintaining the packer-cloudstack project since they are working on integrating terraform with cloudstack. So, please do let me know when I can give them the news :)

**Comment by wico** [comment]
As packer-cloudstack inherited the MPL2-0 license from the original packer tree, I personally think its not possible to re-license it (at least we are not allowed to do so afaik).

**Comment by miguelaferreira** [comment]
I've checked with a colleague that is part of the Apache Foundation and his interpretation was that, since the packer-cloudstack project has its own code base (i.e. it does not share code with the "parent" project), ti would be fine to have a different license.

But as I said, if checking this is too much trouble, or you guys just don't feel comfortable doing it, that's fine. We can work with the Mozilla license.

**Comment by wico** [comment]
I think some code is shared (cloned) and reused from packer, thus I would stay with the MPL2-0 - however:

Its up to @mindjiver to transfer the repo and fiddle with licenses as @mindjiver's is the most up-to-date repo anyway (the version at klarna is 10 commits behind mindjiver:master).

I again say thanks for taking care of all this!

**Comment by dduportal** [comment]
Just to let you know that i'm interested to help, since I have access to a cloudstack instance in our private IaaS, and using the plugin.

**Comment by miguelaferreira** [comment]
@dduportal you are very welcome to help in any way you can
