### ISSUE TITLE
VMs are not expunged after being destroyed

### ISSUE THREAD

**Issue by priezz** [MissionCriticalCloud/vagrant-cloudstack#74]
The problem is that is becomes impossible to automatically recreate the machine without expunging it in the CloudStack. Is it possible to do that with some option?

**Comment by j00p34** [comment]
currently not. I believe cloudstack does expunge automatically in a thread. I'll look in to creating an option

**Comment by priezz** [comment]
> I believe cloudstack does expunge automatically in a thread

Unfortunately not always. It depends on CloudStack management settings and could not be controlled in case of using an external CloudStack provider like I do.

P.S. The rest of the thing works like a charm! Thanks a lot for that. Currently for me it is much more easier to use vagrant than, let's say, ansible to manage machine clusters in the cloud.
