### ISSUE TITLE
Set cloudstack template via config.vm.box attribute

### ISSUE THREAD

**Issue by miguelaferreira** [MissionCriticalCloud/vagrant-cloudstack#79]
Currently the template to use is set in a cloudstack specific attribute, but since vagrant requires a box to be set, one has to set that to a valid box (e.g. the dummy box found in the plugin).

It would be better to set the template to use via the config.vm.box atribute.

**Comment by j00p34** [comment]
@miguelaferreira I believe this is fixed by #105 can we close this?

**Comment by miguelaferreira** [comment]
Yes! Next time just do it. (We an always reopen if needed.)
