### ISSUE TITLE
Destroying VM with Static NAT and Firewall Rules

### ISSUE THREAD

**Issue by Lavaburn** [MissionCriticalCloud/vagrant-cloudstack#80]
When destroying a VM, the code will first remove static NAT and then tries to remove firewall rules.
It however fails on this step, as static NAT removal automatically removes firewall rules [TESTED ON CLOUDSTACK 4.4.3].

Commented lines 66-92 in action/terminate_instance.rb to get around the issue, though it is probably not a correct fix in all scenarios. Possibly removing firewall rules before static nat would work?

**Comment by miguelaferreira** [comment]
Hi @Lavaburn 
Thanks for opening this issue. We will investigate and fix accordingly.
But feel free to make a PR, contributions are always welcome.

Cheers,

**Comment by atsaki** [comment]
Hi @Lavaburn , @miguelaferreira 

Thanks for reporting this issue. I could reproduce this issue on CCP 4.3.0.2.

disableStaticNAT seems to remove all firewall rules on the IP.
- https://issues.apache.org/jira/browse/CLOUDSTACK-99
- https://github.com/apache/cloudstack/blob/770297e8cb14fea4dae2f5f0bfd8aaefa8ea0aa3/server/src/com/cloud/network/rules/RulesManagerImpl.java

Removing firewall rules before static nat worked our environment.

I'll make a PR.
