### ISSUE TITLE
Is it possible to have the public port for SSH randomly generated?

### ISSUE THREAD

**Issue by miguelaferreira** [MissionCriticalCloud/vagrant-cloudstack#85]
And have some kind of clash protection?

**Comment by j00p34** [comment]
why random? Sequential would be easier I guess. (take the first free port)

**Comment by miguelaferreira** [comment]
Because that would mean having to read the existing entries and then calculating a new port. Random would mean that you simply generate a number and use that. Most if the times it will be ok, say the laws of probabilities, and when it is not ok (you get an API error), you repeat the same process until you hit a new port. This way you never need to read the entries in the table.

**Comment by bheuvel** [comment]
@miguelaferreira PR merged, closing.
