### ISSUE TITLE
Add windows VM support

### ISSUE THREAD

**Issue by miguelaferreira** [MissionCriticalCloud/vagrant-cloudstack#93]
Test if a windows template in ACS with vagrant/vagrant credentials works.
If that works:
- Investigate which ACS API call returns the generated password, or how we enable that in a API call
- Investigate how vagrant passes on configuration to winrm communicator (https://github.com/mitchellh/vagrant/tree/d7eaf503298014a93e1faa8da88947bc7d32ba58/plugins/communicators/winrm)
- In the plugin have an action (similar to SSH) that reads the config that comes from the Vagrantfile and creates a environment data structure with the correct credentials (vagrant-cloudstack/action/read_ssh_info.rb)
- In the action module refine the action that reads the winrm config, but also the action that uses winrm to communicate (vagrant-cloudstack/action.rb)

**Comment by bheuvel** [comment]
WIP in https://github.com/bheuvel/vagrant-cloudstack/tree/winrm

Added winrm capability to the plugin.
Apparently winrm seems broken with latest Vagrant development (master). Works with v1.7.2

**Comment by bheuvel** [comment]
- ~~Investigate how vagrant passes on configuration to winrm communicator (https://github.com/mitchellh/vagrant/tree/d7eaf503298014a93e1faa8da88947bc7d32ba58/plugins/communicators/winrm)~~
  Information is passed on via ReadWinrmInfo
- ~~In the plugin have an action (similar to SSH) that reads the config that comes from the Vagrantfile and creates a environment data structure with the correct credentials (vagrant-cloudstack/action/read_ssh_info.rb)~~
  read_ssh_info.rb duplicated (mostly) to read_winrm_info.rb
- ~~In the action module refine the action that reads the winrm config, but also the action that uses winrm to communicate (vagrant-cloudstack/action.rb)~~
  Added :ReadWinrmInfo to action.rb

By extending plugin.rb with a winrm capability, this plugin will be queried by vagrant for support for winrm.

Creation of a Windows guest, works without errors (including winrm testing is vm is operational)
This requires a template with vagrant/vagrant.
- Investigate which ACS API call returns the generated password, or how we enable that in a API call
  This will eliminate need for vagrant/vagrant

**Comment by bheuvel** [comment]
(Currently using Fog 1.22.0)

As of Fog version 1.27.0, a job_id is returned with server creation which holds the generated password.
As of Fog version 1.24.0 the cloudstack attribute 'network_ids' may not be passed as an array (at least with a single entry), else cloudstack will return an authentication error!

So to proceed, would like to jump to Fog (at least) 1.27.0 ...(which at least needs correction of the 'network_ids' handling).

**Comment by j00p34** [comment]
Hey Bob,

Stuur even een berichtje als je binnen bent. (en waar zit je precies?)

Grt. Timothy

**Comment by bheuvel** [comment]
WIP in https://github.com/bheuvel/vagrant-cloudstack/tree/winrm
More updates can (only) be found there

Bumped Fog (1.32.0), creation now completes successfully with the retrieved password.

**Comment by bheuvel** [comment]
@miguelaferreira @j00p34 
Next step in full Windows support is the SyncedFolders support for WinRM.

For this the plugin 'vagrant-winrm-syncedfolders' can be used.

For using this on a Windows host, an issue with file locks has been resolved in in WinRM-FS in [PR17](https://github.com/WinRb/winrm-fs/pull/17). Has already been merged with master and will be available in ( >0.2.0) 0.2.1.

On Linux this already works (less strict by default with file handles/locks)

**Comment by bheuvel** [comment]
@miguelaferreira In general Windows support has been implemented with PR #96 
Closing this and propose to open specific/new requests in separate/new issues.
(Or re-open this one if you feel otherwise :wink: )

**Comment by miguelaferreira** [comment]
Agree!
