### ISSUE TITLE
Is cloudstack.iso_id an alternative to cloudstack.template_id ?

### ISSUE THREAD

**Issue by b-long** [MissionCriticalCloud/vagrant-cloudstack#94]
I've used **`cloudstack.template_id`** for a while with success, however I'd like to use an ISO (a subtype of template as far as I can tell) and I'm not quite sure the proper way to do that.  If I set **`cloudstack.template_id`** to a valid ISO id, I receive an error that CloudStack can't find that template. If I set **`cloudstack.iso_id`** ,  I receive an error that says 

``` error
Unable to execute API command deployvirtualmachine due to missing parameter templateid
```

**Comment by miguelaferreira** [comment]
HI @b-long 

vagrant-cloudstack does not have an iso_id parameter.
If you need to install form ISO my bets guess is that you need to create a template from that ISO, and then use the template_id

**Comment by b-long** [comment]
@miguelaferreira Yes, sorry about not understanding that earlier on.  I was able to create a template from the ISO, and then use that template_id to provision VMs.  Closing this question now that I understand the workflow.
